# Generated by Django 2.1 on 2018-09-03 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180903_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.User'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post',
            field=models.TextField(blank=True, default=''),
        ),
    ]
